### ISSUE TITLE
所以路径放client.py中scf_servers变量哪个位置呢大佬

### ISSUE THREAD

**Issue by pykiller** [shimmeris/SCFProxy#1]

**Comment by shimmeris** [comment]
不是很明白你的含义。
只放一个区域的话：scf_servers = ('https://service-xxx.sh.apigw.tencentcs.com/release/xxx')
两个区域就逗号分隔：scf_servers = ('https://service-xxx1.sh.apigw.tencentcs.com/release/xxx', 'https://service-xxx2.gz.apigw.tencentcs.com/release/xxx')

**Comment by pykiller** [comment]
> 不是很明白你的含义。
> 只放一个区域的话：scf_servers = ('https://service-xxx.sh.apigw.tencentcs.com/release/xxx')
> 两个区域就逗号分隔：scf_servers = ('https://service-xxx1.sh.apigw.tencentcs.com/release/xxx', 'https://service-xxx2.gz.apigw.tencentcs.com/release/xxx')

真相了。我粘贴错了，谢谢大佬
