### ISSUE TITLE
SCFProxy HTTP问题请教

### ISSUE THREAD

**Issue by ltfafei** [shimmeris/SCFProxy#14]
师傅，脚本在中的SCF_TOKEN = "Token"，自定义就可以吧；scf_servers: List[str] = []  #这个列表中填应该是填访问路径的地址。但运行之后报这个错：
![image](https://user-images.githubusercontent.com/43526141/140950180-a55f8022-1daf-4c09-ad4c-aac122a3e21f.png)

**Comment by shimmeris** [comment]
是在 VPS 上运行的吗，有加 `--set block_global=false` 这个参数吗

**Comment by ltfafei** [comment]
> 是在 VPS 上运行的吗，有加 `--set block_global=false` 这个参数吗

确实在VPS上，忘记加这个参数了。
