### ISSUE TITLE
socks代理实现多个API调度

### ISSUE THREAD

**Issue by brucegraland** [shimmeris/SCFProxy#15]
大佬，socks代理能像HTTP代理一样实现多个API调度吗？有思路的话能不能指点一下

**Comment by shimmeris** [comment]
可以是可以，跟 HTTP 一样。

https://github.com/shimmeris/SCFProxy/blob/9a9850e5568cd4b4ceaaeaa6aba4f2269e00b4bf/SOCKS5/src/socks_client/socks5.py#L14-L27

把函数最后一行的 `args.scf_url` 改为从列表中随机获取就可以了。不过因为 SOCK5 是代理的长连接，最长 15m 才会重连一次，
所以没有像 HTTP 一样去做。
