### ISSUE TITLE
关于HTTPS代理

### ISSUE THREAD

**Issue by Dr-S1x17** [shimmeris/SCFProxy#16]
平时还是HTTPS的网站遇见的比较多一点 请问师傅关于HTTPS的实现方式有什么好的思路吗

**Comment by Dr-S1x17** [comment]
打扰了 原来师傅是用mitmproxy实现的

**Comment by shimmeris** [comment]
可以看看 [w13scan](https://github.com/w-digital-scanner/w13scan)，这位师傅自己写的 HTTPS，我这个小项目就不重新发明轮子了。
