### ISSUE TITLE
工具代理SSL问题

### ISSUE THREAD

**Issue by zhimiyouwu33** [shimmeris/SCFProxy#17]
你好师傅：

在尝试搭建云函数代理的时候翻阅到师傅的分享，感谢分享。
请问当使用扫描工具类要调用此HTTP代理客户端接口 时（非浏览器调用），如何实现能正常代理SSL流量问题呢？

**Comment by shimmeris** [comment]
实现 HTTPS 服务器，本地安装生成的自定义证书
