### ISSUE TITLE
in script client.py: cannot import name 'Headers' from 'mitmproxy.net.http'

### ISSUE THREAD

**Issue by relaxcn** [shimmeris/SCFProxy#18]
Loading script client.py
in script client.py: cannot import name 'Headers' from 'mitmproxy.net.http' (/usr/local/lib/python3.10/site-packages/mitmproxy/net/http/__init__.py)

**Comment by shimmeris** [comment]
mitmproxy 7 以上版本将 Headers 移到了 mitmproxy/http.py。

尝试 pull 该项目新版本或重新安装 mitmproxy 6 及一下的版本即可。
