### ISSUE TITLE
请问uvloop不支持windows（VPS）还有虚拟环境是必须的嘛？

### ISSUE THREAD

**Issue by rootGH** [shimmeris/SCFProxy#19]
VPS是Windows安装requirements.txt有个pip uvloop 不支持Windows

**Comment by shimmeris** [comment]
虚拟环境并不是必须的，如果您需要在 Windows VPS 上运行 SOCKS 的话，可以删除 requirements.txt 中的 uvloop 及相关的代码

https://github.com/shimmeris/SCFProxy/blob/81b577c9c17bd9d1cf2c440b4487d8c131e13ea2/SOCKS5/src/socks_client/socks5.py#L6

以及

https://github.com/shimmeris/SCFProxy/blob/81b577c9c17bd9d1cf2c440b4487d8c131e13ea2/SOCKS5/src/socks_client/socks5.py#L118
