### ISSUE TITLE
http版本内存占用高

### ISSUE THREAD

**Issue by tomsux** [shimmeris/SCFProxy#23]
Out of memory: Killed process 4445 (mitmdump) total-vm:4014080kB

http版本内存占用稳定增长,似乎不会释放,我现在的策略是每隔一小时重启mitmdump,不晓得是不是这个版本的问题.

Mitmproxy: 7.0.4
Python:    3.8.10
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Linux-5.4.0-100-generic-x86_64-with-glibc2.29

**Comment by shimmeris** [comment]
http 版本可以说是 mitmdump 的一个插件，所以如果是内存占用增长的话目前属于 mitmdump 的问题。
