### ISSUE TITLE
 连接代理，出现乱码

### ISSUE THREAD

**Issue by longzaizai001** [shimmeris/SCFProxy#24]
![image](https://user-images.githubusercontent.com/95325324/165218912-dc6ffdcc-14e5-45ab-b7c0-73a264ecd5ef.png)

**Comment by shimmeris** [comment]
什么网站，开的什么类型代理，有没有报错

**Comment by renblog** [comment]
转发到burp上就好了

**Comment by ctrlbbj** [comment]
在添加这个修复以后，火狐浏览器通过代理时出现“内容编码错误”

**Comment by gdszps** [comment]
一样出现这种问题
