### ISSUE TITLE
http方式的云函数执行报错

### ISSUE THREAD

**Issue by vvanglro** [shimmeris/SCFProxy#29]
请求api调用云函数时报错了，会返回430的状态码，并将报错的栈用做response返回，我在浏览器上使用代理时报错了会显示出一堆报错栈，一开始我并不知道是哪里出的问题，后来排查是云函数执行的报错，所以在mitmproxy进行response时增加对430的处理。![image](https://user-images.githubusercontent.com/43594924/171950759-9f02e427-c171-476a-8f75-adb89868773a.jpeg)

**Comment by shimmeris** [comment]
后续版本已有对 430 响应码的处理，暂时还未推送
