### ISSUE TITLE
win10 python 3.10.4 安装依赖出现问题

### ISSUE THREAD

**Issue by Chinakentgao** [shimmeris/SCFProxy#30]
搜索了各种解决方案没成功，只能来求助下作者了。
pip install ruamel.yaml.clib==0.2.2
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting ruamel.yaml.clib==0.2.2
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/fa/a1/f9c009a633fce3609e314294c7963abe64934d972abea257dce16a15666f/ruamel.yaml.clib-0.2.2.tar.gz (179 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: ruamel.yaml.clib
  Building wheel for ruamel.yaml.clib (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [90 lines of output]
      sys.argv ['C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-jdwujm1g\\ruamel-yaml-clib_cf64453edc5d45e2bf86e960cd0b2814\\setup.py', 'bdist_wheel', '-d', 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-wheel-9qow3kej']
      test compiling test_ruamel_yaml
      test_ruamel_yaml.c
      Generating code
      Finished generating code
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\ruamel
      copying .ruamel\__init__.py -> build\lib.win-amd64-cpython-310\ruamel
      creating build\lib.win-amd64-cpython-310\ruamel\yaml
      copying .ruamel\yaml\__init__.py -> build\lib.win-amd64-cpython-310\ruamel\yaml
      creating build\lib.win-amd64-cpython-310\ruamel\yaml\clib
      copying .\__init__.py -> build\lib.win-amd64-cpython-310\ruamel\yaml\clib
      copying .\LICENSE -> build\lib.win-amd64-cpython-310\ruamel\yaml\clib
      running build_ext
      building '_ruamel_yaml' extension
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Python\Python310\include -IC:\Python\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tc_ruamel_yaml.c /Fobuild\temp.win-amd64-cpython-310\Release\_ruamel_yaml.obj
      _ruamel_yaml.c
      c:\users\administrator\appdata\local\temp\pip-install-jdwujm1g\ruamel-yaml-clib_cf64453edc5d45e2bf86e960cd0b2814\_ruamel_yaml.h(10): warning C4005: 'PyString_CheckExact': macro redefinition
      _ruamel_yaml.c(486): note: see previous definition of 'PyString_CheckExact'
      _ruamel_yaml.c(1889): warning C4090: '=': different 'const' qualifiers
      _ruamel_yaml.c(3389): warning C4028: formal parameter 2 different from declaration
      _ruamel_yaml.c(3389): warning C4028: formal parameter 3 different from declaration
      _ruamel_yaml.c(3389): warning C4028: formal parameter 4 different from declaration
      _ruamel_yaml.c(3863): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(3961): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4096): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4106): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4116): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4178): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4188): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4198): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4945): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4955): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4965): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(5008): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(5018): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(5028): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(7908): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(7918): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(7928): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(7971): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(7981): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(7991): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(10785): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(10795): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(10805): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(11235): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(11245): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(11255): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(11688): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(11698): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(11708): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12176): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12186): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12196): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12239): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12249): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12259): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12836): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12846): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12856): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13317): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13327): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13337): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13461): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13471): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13481): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13951): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13961): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13971): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(14482): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      _ruamel_yaml.c(15019): warning C4028: formal parameter 2 different from declaration
      _ruamel_yaml.c(15019): warning C4028: formal parameter 3 different from declaration
      _ruamel_yaml.c(17287): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      _ruamel_yaml.c(21581): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      _ruamel_yaml.c(23880): error C2105: '++' needs l-value
      _ruamel_yaml.c(23882): error C2105: '--' needs l-value
      _ruamel_yaml.c(24053): error C2105: '++' needs l-value
      _ruamel_yaml.c(24055): error C2105: '--' needs l-value
      _ruamel_yaml.c(26224): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      c:\python\python310\include\cpython/unicodeobject.h(446): note: see declaration of '_PyUnicode_get_wstr_length'
      _ruamel_yaml.c(26240): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      c:\python\python310\include\cpython/unicodeobject.h(446): note: see declaration of '_PyUnicode_get_wstr_length'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ruamel.yaml.clib
  Running setup.py clean for ruamel.yaml.clib
Failed to build ruamel.yaml.clib
Installing collected packages: ruamel.yaml.clib
  Running setup.py install for ruamel.yaml.clib ... error
  error: subprocess-exited-with-error

  × Running setup.py install for ruamel.yaml.clib did not run successfully.
  │ exit code: 1
  ╰─> [92 lines of output]
      sys.argv ['C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-jdwujm1g\\ruamel-yaml-clib_cf64453edc5d45e2bf86e960cd0b2814\\setup.py', 'install', '--record', 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-record-k0gtkirz\\install-record.txt', '--single-version-externally-managed', '--compile', '--install-headers', 'C:\\Python\\Python310\\Include\\ruamel.yaml.clib']
      test compiling test_ruamel_yaml
      test_ruamel_yaml.c
      Generating code
      Finished generating code
      running install
      C:\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\ruamel
      copying .ruamel\__init__.py -> build\lib.win-amd64-cpython-310\ruamel
      creating build\lib.win-amd64-cpython-310\ruamel\yaml
      copying .ruamel\yaml\__init__.py -> build\lib.win-amd64-cpython-310\ruamel\yaml
      creating build\lib.win-amd64-cpython-310\ruamel\yaml\clib
      copying .\__init__.py -> build\lib.win-amd64-cpython-310\ruamel\yaml\clib
      copying .\LICENSE -> build\lib.win-amd64-cpython-310\ruamel\yaml\clib
      running build_ext
      building '_ruamel_yaml' extension
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Python\Python310\include -IC:\Python\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tc_ruamel_yaml.c /Fobuild\temp.win-amd64-cpython-310\Release\_ruamel_yaml.obj
      _ruamel_yaml.c
      c:\users\administrator\appdata\local\temp\pip-install-jdwujm1g\ruamel-yaml-clib_cf64453edc5d45e2bf86e960cd0b2814\_ruamel_yaml.h(10): warning C4005: 'PyString_CheckExact': macro redefinition
      _ruamel_yaml.c(486): note: see previous definition of 'PyString_CheckExact'
      _ruamel_yaml.c(1889): warning C4090: '=': different 'const' qualifiers
      _ruamel_yaml.c(3389): warning C4028: formal parameter 2 different from declaration
      _ruamel_yaml.c(3389): warning C4028: formal parameter 3 different from declaration
      _ruamel_yaml.c(3389): warning C4028: formal parameter 4 different from declaration
      _ruamel_yaml.c(3863): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(3961): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4096): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4106): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4116): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4178): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4188): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4198): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4945): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4955): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(4965): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(5008): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(5018): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(5028): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(7908): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(7918): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(7928): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(7971): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(7981): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(7991): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(10785): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(10795): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(10805): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(11235): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(11245): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(11255): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(11688): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(11698): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(11708): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12176): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12186): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12196): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12239): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12249): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12259): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12836): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12846): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(12856): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13317): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13327): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13337): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13461): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13471): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13481): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13951): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13961): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(13971): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
      _ruamel_yaml.c(14482): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      _ruamel_yaml.c(15019): warning C4028: formal parameter 2 different from declaration
      _ruamel_yaml.c(15019): warning C4028: formal parameter 3 different from declaration
      _ruamel_yaml.c(17287): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      _ruamel_yaml.c(21581): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      _ruamel_yaml.c(23880): error C2105: '++' needs l-value
      _ruamel_yaml.c(23882): error C2105: '--' needs l-value
      _ruamel_yaml.c(24053): error C2105: '++' needs l-value
      _ruamel_yaml.c(24055): error C2105: '--' needs l-value
      _ruamel_yaml.c(26224): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      c:\python\python310\include\cpython/unicodeobject.h(446): note: see declaration of '_PyUnicode_get_wstr_length'
      _ruamel_yaml.c(26240): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      c:\python\python310\include\cpython/unicodeobject.h(446): note: see declaration of '_PyUnicode_get_wstr_length'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> ruamel.yaml.clib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by Chinakentgao** [comment]
我尝试安装0.2.6版本安装成功了 不知道会不会影响代码执行

**Comment by Chinakentgao** [comment]
一堆问题处理完访问ipip.net正常但是访问百度 huawei qq全部都是内容编码错误
![图片](https://user-images.githubusercontent.com/55339757/171983644-39006581-98e7-43f4-bf54-3b6a090d2d63.png)

**Comment by shimmeris** [comment]
试试 chrome， firefox 存在点问题 #24

**Comment by Chinakentgao** [comment]
已经解决了 br编码的情况下会出现这个问题直接把br编码去掉就行了 直接在server端处理
3.10不支持ruamel.yaml.clib==0.2.2&nbsp; 安装时需要去掉版本要求安装最新版本





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月7日(星期二) 下午3:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shimmeris/SCFProxy] win10 python 3.10.4 安装依赖出现问题 (Issue #30)





 
试试 chrome， firefox 存在点问题 #24

**Comment by shimmeris** [comment]
已更新解决方案

**Comment by Chinakentgao** [comment]
我试过引用最新版本的requests库依旧存在这个问题。大概率是现在的requests库bug吧！你可以试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月7日(星期二) 下午3:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shimmeris/SCFProxy] win10 python 3.10.4 安装依赖出现问题 (Issue #30)





 
是的，因为服务端 Python 的 requests 版本低，不支持 br，去掉也算是个临时解决方案
