### ISSUE TITLE
http代理 乱码

### ISSUE THREAD

**Issue by gdszps** [shimmeris/SCFProxy#31]
https://www.mercadolivre.com.br/ 
别的站都没问题 就这个站有问题

���r�X� ����pd��,$���CJ�DW����^��P�@$�L��ںm���lz���lf���Ǧ,ˬ��������>aιpA�"�<�#�!b������܃_�~�w�{����4G��/^���@�ǡ��T�g���~�����o9�·L�u-3���o�uy�㠙�___��7p,�p �6�� gz#9�j�Uj���ȍ,�4z�cw��*�o17r�Ѐ�~~gs]+�o�C)�[�7�u�?W}���}m�=�:wt�~x�!���Cv�\�l��I�t'� �,+r�2�p�5F9�W�h]+�W��{����۴����u��N��L���~�רX�U�[��aB9c<��0~��߃�Z�R.T�b�ݹ=��f��+hZ��P��7��0�ݑ����;������[�m�C��>h��+ܼ;�i�u*�ޕ��)t��1u�ǉ5�(�����=��3��z�R���^�`��8!����ԝ8�Ö��7�Y�G;��M�g�������]>�tN<ݏ�vb�Ź~ؚ���q��o�qb��ޟ�d�3�b)n���K~��~�u�^f�_�t��﬛��A���e�4'���+%k񪤠vya]n�V8�����>(�U�>����ݐ9DYב��$�#˪�϶��������nα�A8��67�0��2u�!s�5/��0{��wȀ��s�� v�:�������@�Tl=�Ȗ%g�JZV `����;L�Y��������(#���c��\+��2B7662Q��W�U@��f�g]��W��j��B��XZ�*��{�� �c�76�̓l���sV ���u���I�#4��ґ6y������t�aUfjd�����}t.�I{���C�=<�k��@ 2iMI�42A,�K>ds=ZW$9cR�.��㋎O_ ��;;��kM/�߻ֵ��5��`�oLk,�P`�ؔ�iMf������9׻�`�K^��XC�����I �6�@12�?����0����zs��@�����˼�DM��á�z����X�p$���Y!�o����ݢ@�Y�7���F�wuk�j� u�OG*�K}�nω(���i��+�2ᮏw�B�茱y.���_i�X�u`Yn� �r.3׳��X=�/����[L��:RI��L��}B�����%\i�-�0{'$䗆����E0�,��^�}Ks2�hX���35X�f����=ÇZ%��� 8u|?�����l�%��( J�r/ƗP��q�q\�ī!+I�����n���*o"��D{���s�P��r$��#�,��K��ȜC�~�F��'��=���Q#8ldM�I0<�̢da��5vW��kQFC���V�2��W��3���?+�7�c����2fWY��(�Atb�D"��u� ,� &4��P�"��з�xR��RP}����G+g��sP0�dpQ�� �PdE�N����q�%��7h�:{ U���lʛ��,v&���23k���{�>XN`I�+��V�{(e�f���=r�)� ��R_M�μq� �ؘ�i����~�(� CBދ�~����4�Ȋg�-�e�yW���- �7%�>h`�mw��7�;^m�ڑ����ʅparqlA G��N���d��ձ�ӏF�T�j,�#~|�S/��k�2�Jo�T��sV؅�����|�:*)��3�~L$�(RwyHAr�U��ˡ**R�23�T��nD`}@�f��;d��Ŝ6 H�S��6/�Rc2�V�\��o}t�\F�y �"jyTE�I��ډu�*��p���� ���m.]�w6Y�0��T�>�nO2ٝ�YL2�ր3g�h#Ii�$��0����ơ��Εm�Hp8Z8�g�L�Cb�������1 ���tl0f��L8Ug���=2��9!�H(��S�Z6ڔ���E���vJW���=������$��$�~�L"�E�a��}�pXǃ�)9�v� ��(�r����B0��s�v��T����\$\��F���hBP3��}�w���p|J� U�Y!�K[����).������K�xLW���1�x(���(�����5)�N6�46��%� t�AVd�wϽ��=�k�Y�[�&�h�㬎���-S�!JK���d��0�9\\%��\pБ�� �^C3ZVp���C6�2\ϽyXv�IM� �H�Mf/m2��b)���=�Cf����"�]�)s�E�R�Z��ڂJ�Щ�Q+�ݔ���{|^ºynlY#��o�pCg״@����+���1��b\*�¡�f�y��C��2�!�>L�*t�L��E�Q�%I���Y��E��� T�11��dv���� �Ƹ����l��q���l�A�x]f������=#4�K�� �Ę\c� ,P�i�Ĉ$�vtbz.�����ol88�`�NyJ3=Ш7�������;LtC��U*�� "�[ɀ�X�%t�Hw�P�yP/@�ss�͙�����Yh���t�K�^j��;��m<�M�W:&�-���Ʃ}q]�-�dU�,vO��?1��w1�J۲�[��x#Z��~l�����P.D��h9�B�.�Z�ˁ�G�옻��KO"\�V��Jd:��J���"S-��� C��z� +�!��S�4I���ec$hg2�@?ɣ��k�ơ�A���,G�����ef��;�]�����f��ſ����f6�����2�]��G����wכ��w�����ۿȃT���{��ݡ�>�‶�!?�7������������}N�cg��2T����}53q�w�m�B%$���,����߀p~�43��]�f�B���R6�S��h����R� �9<E�b�f�!�M)=E9B�,�9�t1���#�*�vb�1ց����m�`c_��� ��1%�U\`p��iF�C�>0�Y�*���U}2���ͬu*Y�+rSso�ӥ�Q���KF/��3O�����~í�~�4'����J?^� �( �u�'��P���ba���A���?�ff��P�63�+8���ʻT����Tz�w�*d� �+m��8p׊u9����8ո���P�rHd&S�u�aN_@��~Ĉ�.@+�"�E@B��$���S��m���L��� Av��q��,�������y�D焚��BU�z0}�me�NP��gb5��gfb�`y�n��ҷ�1�+ �0߷��oT ��cۖ��S\k���C�wu/3�{-4V�YЦ�N�� 'r��b�1-��%/�ٗ[L�M�4��\�ANO����YT�/��3B�O"ΒjV����/Uw<�I���m-u�adܸ4LÌQ��RI��� �0l�D�F�w��Lt���g�'"�"k*;ͼä>D���L����A j�Q�S\��f��1���b���G妜��N��ؐb&;�%y�V���)��nXz= ������mD���TC*"_��=�!

**Comment by gdszps** [comment]
`def request(flow: mitmproxy.http.HTTPFlow):
    scf_server = choice(scf_servers)
    request = flow.request
    myheaders=dict(request.headers)
    myheaders["Accept-Encoding"]= ""
    data = {
        "method": request.method,
        "url": request.pretty_url,
        "headers": myheaders,
        "body": b64encode(request.raw_content).decode('utf-8'),
    }
    flow.request = flow.request.make(
        "POST",
        url=scf_server,
        content=json.dumps(data),
        headers={
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Encoding": "gzip, deflate, compress",
            "Accept-Language": "en-us;q=0.8",
            "Cache-Control": "max-age=0",
            "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36",
            "Connection": "Keep-Alive",
            "Host": urlparse(scf_server).netloc,
        },
    )`
把 "Accept-Encoding"删了 就能跑通

**Comment by shimmeris** [comment]
由服务端返回的 headers 中 `content-length` 头为小写，客户端中获取的为大写
https://github.com/shimmeris/SCFProxy/blob/d7ef47162ea5549e23619d344e79fa3ba0c7a64e/HTTP/src/client.py#L86
