### ISSUE TITLE
超时那里有bug

### ISSUE THREAD

**Issue by nvv5** [shimmeris/SCFProxy#4]
https://github.com/shimmeris/SCFProxy/blob/5622af876bb8330283bfcb1d547e7312b3ffed0e/HTTP/src/client.py#L55-L57

这里报错content不能是元组，我改成了
```
flow.response.text = "<html><body>操作已超过云函数服务最大时间限制，可在函数配置中修改执行超时时间</body></html>"
```

**Comment by shimmeris** [comment]
感谢提交的 bug，black 格式化的时候给自动换行了
