### ISSUE TITLE
can't access google

### ISSUE THREAD

**Issue by leezp** [shimmeris/SCFProxy#6]
tencent cloud api can't support http2 ，how to let it be a http proxy for google.com?

**Comment by shimmeris** [comment]
When creating serverless cloud functions, you can select regions other than mainland China, such as Hongkong, Singapore. Then you can access google(in theory, did not try). Please tell me if you can :).

**Comment by leezp** [comment]
i tried， only curl worked ，browser http proxy doesn’t work



发自我的iPhone


------------------ Original ------------------
From: Mio ***@***.***&gt;
Date: Tue,Jun 1,2021 11:55 PM
To: shimmeris/SCFProxy ***@***.***&gt;
Cc: Lee ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [shimmeris/SCFProxy] can't access google (#6)





 
When creating serverless cloud functions, you can select regions other than mainland China, such as Hongkong, Singapore. Then you can access google(in theory, did not try). Please tell me if you can :).

**Comment by shimmeris** [comment]
Maybe your browser didn't use the proxy, you can access `http://myip.ipip.net` multiple times to check whether the IP address varies.

**Comment by leezp** [comment]
of coure!&nbsp;
Varied



发自我的iPhone


------------------ Original ------------------
From: Mio ***@***.***&gt;
Date: Wed,Jun 2,2021 11:11 AM
To: shimmeris/SCFProxy ***@***.***&gt;
Cc: Lee ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [shimmeris/SCFProxy] can't access google (#6)





 
Maybe your browser didn't use the proxy, you can access http://myip.ipip.net multiple times to check whether the IP address varies.
