### ISSUE TITLE
sock5模式

### ISSUE THREAD

**Issue by leezp** [shimmeris/SCFProxy#7]
用curl测试。vps sock5 显示established，且curl有响应。 但云函数报错；
![image](https://user-images.githubusercontent.com/16287528/120583186-4fd20300-c460-11eb-8e72-1a87ce721cf4.png)
是代码小bug吗

**Comment by shimmeris** [comment]
有修改云函数超时时间吗，看上去像是设置的 60s 超时，然后强制中断了

**Comment by leezp** [comment]
改了60，这里的提示也是60s

**Comment by shimmeris** [comment]
改成 900 即可

**Comment by leezp** [comment]
60 已经可以返回响应了，但云函数那里一直在加载，很奇怪

**Comment by shimmeris** [comment]
加载是正常的，SOCKS5 是长连接，云函数服务端用了个 while 循环来同步 IO，会一直执行直到超时。然后重新开启一个新的 SOCKS5 连接。
